<?php

namespace App\Helpers;

use Illuminate\Support\Facades\DB;
use PDO;

class DatabaseBackupHelper
{
    // Sirf PDO method use karo - yeh Windows par bhi kaam karega
    public static function generateMysqlDump(): string
    {
        $filename = storage_path("app/backups/dump-" . date('Y-m-d-H-i-s') . ".sql");
        
        if (!is_dir(dirname($filename))) {
            mkdir(dirname($filename), 0755, true);
        }
        
        $pdo = DB::connection()->getPdo();
        
        // Get all tables
        $tables = $pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
        
        $output = "-- MySQL dump generated by CMS Portal\n";
        $output .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
        $output .= "SET NAMES utf8mb4;\n";
        $output .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";
        
        foreach ($tables as $table) {
            // Drop table statement
            $output .= "DROP TABLE IF EXISTS `$table`;\n";
            
            // Get CREATE TABLE statement
            $createStmt = $pdo->query("SHOW CREATE TABLE `$table`")->fetch(PDO::FETCH_ASSOC);
            $output .= $createStmt['Create Table'] . ";\n\n";
            
            // Get all rows
            $rows = $pdo->query("SELECT * FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);
            
            if (!empty($rows)) {
                foreach ($rows as $row) {
                    $columns = array_keys($row);
                    $values = array_map(function($val) use ($pdo) {
                        if ($val === null) return 'NULL';
                        return $pdo->quote($val);
                    }, array_values($row));
                    
                    $output .= "INSERT INTO `$table` (`" . implode("`, `", $columns) . "`) VALUES (" . implode(", ", $values) . ");\n";
                }
                $output .= "\n";
            }
        }
        
        $output .= "SET FOREIGN_KEY_CHECKS = 1;\n";
        
        file_put_contents($filename, $output);
        
        // Create zip file
        $zipFilename = str_replace('.sql', '.zip', $filename);
        $zip = new \ZipArchive();
        if ($zip->open($zipFilename, \ZipArchive::CREATE) === TRUE) {
            $zip->addFile($filename, basename($filename));
            $zip->close();
            // Remove the SQL file after zipping
            unlink($filename);
            return $zipFilename;
        }
        
        return $filename; // fallback to SQL if zip fails
    }
    
    public static function restoreDump(string $zipFilePath): bool
    {
        if (!file_exists($zipFilePath)) {
            throw new \Exception("Backup file not found: {$zipFilePath}");
        }
        
        // Extract SQL file from zip
        $zip = new \ZipArchive();
        if ($zip->open($zipFilePath) === TRUE) {
            $tempDir = sys_get_temp_dir() . '/cms_backup_' . uniqid();
            mkdir($tempDir, 0755, true);
            
            $zip->extractTo($tempDir);
            $zip->close();
            
            // Find the SQL file
            $sqlFiles = glob($tempDir . '/*.sql');
            if (empty($sqlFiles)) {
                throw new \Exception("No SQL file found in backup");
            }
            
            $sqlFilePath = $sqlFiles[0];
        } else {
            throw new \Exception("Could not open backup file");
        }
        
        $sql = file_get_contents($sqlFilePath);
        
        // Clean up temp files
        unlink($sqlFilePath);
        rmdir($tempDir);
        
        // Split SQL into individual statements
        $statements = self::splitSqlStatements($sql);
        
        $pdo = DB::connection()->getPdo();
        
        try {
            $pdo->beginTransaction();
            
            // Drop all existing tables first
            $tables = $pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
            $pdo->exec("SET FOREIGN_KEY_CHECKS = 0");
            foreach ($tables as $table) {
                $pdo->exec("DROP TABLE IF EXISTS `$table`");
            }
            $pdo->exec("SET FOREIGN_KEY_CHECKS = 1");
            
            // Execute each statement
            foreach ($statements as $statement) {
                $statement = trim($statement);
                if (!empty($statement)) {
                    $pdo->exec($statement);
                }
            }
            
            $pdo->commit();
            return true;
            
        } catch (\Exception $e) {
            $pdo->rollBack();
            throw new \Exception("Restore failed: " . $e->getMessage());
        }
    }
    
    private static function splitSqlStatements(string $sql): array
    {
        $statements = [];
        $current = '';
        
        $lines = explode("\n", $sql);
        foreach ($lines as $line) {
            $line = trim($line);
            if (empty($line)) continue;
            
            $current .= $line . "\n";
            
            if (substr(rtrim($line), -1) === ';') {
                $statements[] = trim($current);
                $current = '';
            }
        }
        
        if (!empty($current)) {
            $statements[] = trim($current);
        }
        
        return $statements;
    }
}